import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({ subsets: ["latin"] });

export default function TermsOfService() {
    return (
        <div className="min-h-screen">
            <main className="container mx-auto px-4 py-16 max-w-4xl">
                <h1 className={`${playfair.className} text-4xl font-bold mb-8`}>Terms of Service</h1>

                <div className="prose max-w-none space-y-12">
                    {/* Liability Section */}
                    <section>
                        <h2 className={`${playfair.className} text-2xl font-semibold mb-4`}>Liability</h2>
                        <div className="space-y-4">
                            <h3 className="text-lg font-medium">No Warranty or Guarantee</h3>
                            <p>We provide this service 'as-is' and without any warranty or guarantee. While we make every effort to ensure the functionality, security, and reliability of our site, we do not make any representations or warranties regarding the accuracy, completeness, or suitability of the information and materials found or offered on this website.</p>

                            <h3 className="text-lg font-medium">Exclusion of Liability</h3>
                            <p>In no event shall we be liable for any direct, indirect, incidental, consequential, special, or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses, resulting from the use or inability to use our services.</p>

                            <h3 className="text-lg font-medium">User Responsibility</h3>
                            <p>You acknowledge and agree that your use of this service is at your own risk. We are not responsible for any damages or issues that may arise, including but not limited to, data loss, system errors, or interruptions in service. It is your responsibility to take appropriate precautions and ensure that any services or information obtained through our site meet your specific requirements.</p>

                            <h3 className="text-lg font-medium">Indemnification</h3>
                            <p>By using this service, you agree to indemnify and hold us harmless from any claims, actions, damages, liabilities, costs, and expenses, including reasonable attorneys' fees, arising out of or in connection with your use of the service or any violation of these terms.</p>
                        </div>
                    </section>

                    {/* AI-Generated Content Section */}
                    <section>
                        <h2 className={`${playfair.className} text-2xl font-semibold mb-4`}>AI-Generated Content</h2>
                        <div className="space-y-4">
                            <h3 className="text-lg font-medium">No Control Over AI Output</h3>
                            <p>We utilize AI technology to generate images based on user inputs. While we strive to provide accurate and appropriate content, we have no control over the specific output of the AI-generated images. The results may vary and may not always meet your expectations.</p>

                            <h3 className="text-lg font-medium">Prohibited Content</h3>
                            <p>You agree not to use our service to generate any content that is NSFW (Not Safe For Work), explicit, or illegal in nature. This includes, but is not limited to, content that is sexually explicit, violent, defamatory, obscene, or infringes on intellectual property rights. Any attempt to generate such content will result in an immediate ban of your account.</p>

                            <h3 className="text-lg font-medium">Disclaimer of Responsibility</h3>
                            <p>We are not responsible for any content generated by users through our application. You acknowledge and agree that you are solely responsible for the content you generate and any consequences that may arise from its use. We disclaim any liability for any harm or damages resulting from user-generated content.</p>
                        </div>
                    </section>

                    {/* Continue with other sections... */}

                    <div className="text-sm text-gray-600 mt-12 pt-8 border-t">
                        <p>Last Modified: 9/23/2024</p>
                    </div>
                </div>
            </main>
        </div>
    );
} 