name: pipeline
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: phantomreactor111/enklipse:enklipse-frontend
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
            NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
            NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
            NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_GOOGLE_SCOPE=${{ secrets.NEXT_PUBLIC_GOOGLE_SCOPE }}
            NEXT_PUBLIC_GOOGLE_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_REDIRECT_URI }}
            NEXT_PUBLIC_AUTH_SECRET_KEY=${{ secrets.NEXT_PUBLIC_AUTH_SECRET_KEY }}
